#!/usr/bin/env python3
"""context_compressor.py — Generate context snapshot templates for TM OS agents."""

import re, sys, subprocess, argparse
from datetime import date
from pathlib import Path

REPO_ROOT     = Path(__file__).parent.parent
DOCS_DIR      = REPO_ROOT / "docs"
MISTAKES_FILE = DOCS_DIR / "MISTAKES.md"
ITERATIONS_FILE = DOCS_DIR / "ITERATIONS.md"
SNAPSHOTS_DIR = REPO_ROOT / "context-snapshots"

DOMAIN_PATHS = {
    "BUILD":   ["Makefile", "tools/", ".cargo/"],
    "HEAD":    ["kernel/src/head/"],
    "TAPE":    ["kernel/src/tape/"],
    "CTRL":    ["kernel/src/ctrl/"],
    "TRANS":   ["kernel/src/trans/"],
    "DEVICE":  ["kernel/src/device/"],
    "DISPLAY": ["kernel/src/display/"],
    "STORE":   ["kernel/src/store/"],
    "PROC":    ["kernel/src/proc/"],
    "SHELL":   ["userspace/"],
    "TEST":    ["tests/"],
}


def git(args):
    try:
        r = subprocess.run(["git"] + args, cwd=REPO_ROOT,
                           capture_output=True, text=True, timeout=15)
        return r.stdout.strip()
    except Exception:
        return ""


def recent_files(domain: str) -> list:
    files = []
    for path in DOMAIN_PATHS.get(domain, []):
        log = git(["log", "--oneline", "-8", "--name-only", "--", path])
        for line in log.split("\n"):
            line = line.strip()
            if line and not re.match(r"^[0-9a-f]{7}", line) and line not in files:
                files.append(line)
    return files[:15]


def domain_mistakes(domain: str) -> list:
    if not MISTAKES_FILE.exists(): return []
    content = MISTAKES_FILE.read_text()
    entries = []
    for m in re.finditer(rf"## \[(MISTAKE-\d+)\] \[([^\]]*{domain}[^\]]*)\] — (.+)", content):
        # Extract prevention rule
        section_match = re.search(
            rf"## \[{re.escape(m.group(1))}\].*?\*\*Prevention Rule:\*\*\s*(.+?)(?=\n\n|\n\*\*|---)",
            content, re.DOTALL
        )
        rule = section_match.group(1).strip() if section_match else "See MISTAKES.md"
        entries.append({"id": m.group(1), "title": m.group(3).strip(), "rule": rule})
    return entries


def recent_iters(domain: str) -> list:
    if not ITERATIONS_FILE.exists(): return []
    content = ITERATIONS_FILE.read_text()
    entries = []
    for m in re.finditer(rf"## \[(ITER-\d+)\] \[{domain}\] — (.+?)\n\*\*.*?Status:\*\* (\w+)", content):
        entries.append(f"- {m.group(1)} [{m.group(3)}]: {m.group(2)}")
    return entries[-5:]


def generate(domain: str, version: int) -> str:
    today       = date.today().isoformat()
    branch      = git(["branch", "--show-current"]) or "unknown"
    files       = recent_files(domain)
    mistakes    = domain_mistakes(domain)
    iters       = recent_iters(domain)
    uncommitted = git(["status", "--short"])

    files_str = "\n".join(f"- {f}" for f in files) if files else "- (none detected — check git log)"
    uncommitted_str = uncommitted if uncommitted else "- None (clean)"

    mistakes_str = "\n".join(
        f"- LOGGED: {m['id']} — {m['title']}\n  Rule: {m['rule']}"
        for m in mistakes
    ) if mistakes else "- None for this domain yet."

    iters_str = "\n".join(iters) if iters else "- No iterations yet."

    return f"""## CONTEXT SNAPSHOT — {domain} — {today} — v{version}
> Branch: {branch} | Generated by tools/context_compressor.py
> FILL IN all [FILL] sections before saving and committing.

---

### ✅ Working State
> What is DONE and tested (QEMU test passed):
- [FILL: e.g., "BumpAllocator: implemented, tape_alloc test passes"]
- [FILL: e.g., "tape/regions.rs: all constants defined"]

> What is IN PROGRESS right now:
- [FILL: e.g., "Slab heap allocator — 60% done"]

> What is NOT started (so I don't assume it's done):
- [FILL: e.g., "Global allocator not registered yet — Box/Vec don't work"]

---

### 🔒 Locked Decisions
> Design choices that must NOT be revisited.
> Format: "LOCKED: [decision] — [reason]"
- LOCKED: All addresses are u32 (32-bit physical) — flat segmentation, no paging
- [FILL: add your specific decisions]

---

### 🔧 Open Problems
> Unresolved questions or blockers.
- OPEN: [FILL or "None — unblocked"]

---

### 📁 Files Changed This Session
> Pre-filled from git (verify accuracy):
{files_str}

> Uncommitted changes:
{uncommitted_str}

---

### ⚠️ Mistakes Found (Domain: {domain})
{mistakes_str}

---

### 📋 Recent Iterations
{iters_str}

---

### ➡️ Next Action
[FILL: Single imperative sentence. E.g., "Implement slab heap in kernel/src/tape/heap.rs and register as global allocator."]

---

### 🚧 Blocking Dependencies
- [FILL: "BLOCKED ON: DOMAIN — what I need" or "None — can proceed"]

---

### 📝 Handoff Note
> 3–5 sentences briefing a cold reader. IMPORTANT: include any 32-bit specific
> gotchas — this is not a standard Rust target and has unusual constraints.

[FILL: E.g., "The bump allocator lives in tape/allocator.rs and grows upward
from KERNEL_HEAP_BASE (0x00300000). It doesn't free. All addresses are physical u32 —
there's no virtual memory. The slab heap needs to be registered as #[global_allocator]
in tape/heap.rs before any Box or Vec calls work."]

---
*Snapshot: {domain} v{version} | {today}*
"""


def main():
    p = argparse.ArgumentParser(description="Generate TM OS context snapshot template")
    p.add_argument("--domain", required=True)
    p.add_argument("--version", required=True, type=int)
    p.add_argument("--print", action="store_true")
    args = p.parse_args()

    domain = args.domain.upper()
    if domain not in DOMAIN_PATHS:
        print(f"Unknown domain '{domain}'. Valid: {list(DOMAIN_PATHS.keys())}")
        sys.exit(1)

    template = generate(domain, args.version)

    if args.print:
        print(template)
        return

    SNAPSHOTS_DIR.mkdir(exist_ok=True)
    today = date.today().isoformat()
    out = SNAPSHOTS_DIR / f"{today}_{domain}_v{args.version}.md"
    out.write_text(template)
    print(f"✅ Snapshot template saved: {out}")
    print(f"\nNext steps:")
    print(f"  1. Open {out} and fill in all [FILL] sections")
    print(f"  2. git add {out} && git commit -m 'context: {domain} v{args.version}'")
    print(f"  3. Start new Cursor session: Bootstrap Prompt + domain MD + this snapshot + dispatch card")

if __name__ == "__main__":
    main()
